name: units test cli

on:
  push:
    paths:
      - 'cli/**'

jobs:
  cli_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: Install dependencies and run tests
        run: |
          cd cli
          yarn
          yarn test:coverage

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
